sudo: required

language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install -qq curl

install:
  - pip install --user -r requirements.txt

script:
  - python hello.py &
  - sudo netstat -antlp
  - curl "http://127.0.0.1:5000"

