sudo: required

services:
  - docker

before_install:
  - sudo apt-get install -qq curl
  - docker pull iaroslavb/flask-helloworld
  - sudo pip install -r requirements.txt
  - python hello.py &

script:
  - sudo netstat -antlp
  - curl "http://127.0.0.1:5000"

